### ISSUE TITLE
Entry point module

### ISSUE THREAD

**Issue by devngc** [pollination/pollination-apps#18]
@mostaphaRoudsari, 
pollination-apps mandates that the entry point module's name has to be "app.py" else it raises an error in CLI. This needs to be relaxed. I have an app where I would like the entry point module to be named "Introduction" or anything I like for that matter.

**Comment by devngc** [comment]
For now, I just disabled [this](https://github.com/pollination/pollination-apps/blob/master/pollination_apps/cli/__init__.py#L106-L109) check locally. I am not sure what's the best alterative for a check for app.py. May be this check should not happen. Else, it will stop anyone from having another name for the entry point module.

**Comment by devngc** [comment]
I thought I could run Pollination-apps locally and just comment out [this](https://github.com/pollination/pollination-apps/blob/master/pollination_apps/cli/__init__.py#L106-L110) check. But when I deployed, I got the message on CLI that the app is successfully deployed to Pollination, but when I headed over to Pollination, there was no app. Only a white screen. I waited 10 mins and refreshed several time. The app wasn't there. I saw 502 in console. This tells me that somewhere other than pollination-apps, "app.py" is hardcoded as a name for the entry point module.

**Comment by mostaphaRoudsari** [comment]
Hi, @devngc - the app.py is hard coded and is not an easy change. Can you use this library to get around the issue:

https://github.com/blackary/st_pages

**Comment by devngc** [comment]
@mostaphaRoudsari, I tried this solution and have to report that it is shaky for now. It does not always work. It would be best to think about removing the hard-coded "app.py"

**Comment by AntoineDao** [comment]
Hi @devngc I am looking into to this now. Before I dive to deep I would need to better understand your use-case. Why does the file have to be renamed to `introduction` in this case?

**Comment by mostaphaRoudsari** [comment]
Hi @AntoineDao - This is mainly because of how the multi-page Streamlit apps work. They use the name of each module for each page. A poor design decision if you ask me but I think they are selling it to keep it simple.

docs.streamlit.io/library/get-started/multipage-apps/create-a-multipage-app#convert-an-existing-app-into-a-multipage-app


Right now the name for the first page of the app will be set `app`. @devngc is trying to set it to a better name like `introduction`.

**Comment by AntoineDao** [comment]
Right, thanks for the docs, that helps me understand the context of this request a bit better 😄

**Comment by devngc** [comment]
Hi @AntoineDao,

I tried to deploy a new version of the app using the latest version of pollination-apps. I had renamed the my entry point module to "Introduction.py". However, I was not able to deploy. I got the following error.

"Error: Application folder is missing a required file: app.py"

**Comment by mostaphaRoudsari** [comment]
That's a check that I put in the CLI. You can either remove it or put a dummy app.py file to deploy your app and then change the settings from the browser

**Comment by devngc** [comment]
Thank you both. Closing the issue.
